dotfiles_repo=$XDG_DATA_HOME/chezmoi
dotfiles=$dotfiles_repo/home
dotfiles_config=$dotfiles/dot_config

# rcs
brc () {
cd $dotfiles_config/bash; v
}
vimrc () {
cd $dotfiles_config/nvim; v
}
rrc () {
cd $dotfiles_config/ranger; v
}
kittyrc () {
cd $dotfiles_config/kitty; v
}
dfrc () {
cd $dotfiles; nvim .chezmoiscripts/run_once_install_dependencies.sh.tmpl
}

# vim
v () {
if [ -f ./Session.vim ] ; then
  nvim -S Session.vim $@
else
  nvim $@
fi
}

function ranger {
  local IFS=$'\t\n'
  local tempfile="$(mktemp -t tmp.XXXXXX)"
  local ranger_cmd=(
    command
    ranger
    --cmd="map Q chain shell echo %d > "$tempfile"; quitall"
  )

  ${ranger_cmd[@]} "$@"
  if [[ -s "$tempfile" ]] && [[ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]]; then
    command zoxide add "$(cat -- "$tempfile")" && cd -- "$(cat -- "$tempfile")" || return
  fi
  command rm -f -- "$tempfile" 2>/dev/null
}

alias g=lazygit
alias d=lazydocker
alias t=taskwarrior-tui
alias r=ranger

alias fd='fd --ignore-case --hidden --follow'
alias rg='rg --smart-case --hidden --follow'

website () {
  p=$DISTROBOX_HOST_HOME/Documents/website
  pn=$p/nim
  kitty @ launch --type=window --cwd=$pn --keep-focus bash -c "nim c --outDir:bin --verbosity:0 --listfullpaths ./tools/build.nim && ./bin/build -w"
  kitty @ launch --type=window --cwd=$pn --keep-focus bash -c "./nimbledeps/bin/nimhttpd -p:8080 ../build"
  kitty @ launch --type=window --cwd=$p/devtools --keep-focus bash -c "npx tailwindcss -i ./prestyles.css -o ../build/styles.css --watch"
  kitty @ launch --type=tab --cwd=$p bash -c "nvim -S Session.vim"
}

backend () {
  p=$DISTROBOX_HOST_HOME/Documents/loockook/loockook_backend
  kitty @ launch --type=tab --cwd=$p --keep-focus bash -l -c "npm run start:dev"
  kitty @ launch --type=tab --cwd=$p --keep-focus bash -l -c "docker compose up"
  kitty @ launch --type=tab --cwd=$p/test --keep-focus bash -l -c "docker compose up"
  cd $p; v
}

frontend () {
  p=$DISTROBOX_HOST_HOME/Documents/loockook/loockook_frontend
  kitty @ launch --type=tab --cwd=$p --keep-focus bash -l -c "npm run start"
  cd $p; v
}

gd () {
if [ -f ./project.godot ] ; then
if [[ "$(top -b -n 1 | grep godot)" ]] ; then
    echo ""
  else
    kitty @ launch --type tab --cwd current --keep-focus godot --editor
    echo "press enter"; read;
  fi
  # task context godot
  # v -c 'norm \ ft'
  v

  # if [ -f ./Session.vim ] ; then
  #   NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim -S Session.vim
  # else
  #   NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim
  # fi
else
  echo "not a godot project"
fi
}

# vim:ft=sh
