-- local g = require 'globals'
-- local add = require 'utils'.addTable
--
-- local ft = 'cmake'
--
-- add(g.lsp.fts, {
--   ft,
-- })
--
-- add(g.lsp.servers.lsp_installer, {
--   cmake = 'default',
-- })
--
-- add(g.treesitter.ensure_installed, {
--   ft,
-- })
